### ISSUE TITLE
Cannot connect on iPhone

### ISSUE THREAD

**Issue by vmdude** [TwidereProject/TwidereX-iOS#107]
Freshly installed on my phone, the app cannot connect through twitter's API, displaying an empty message box with an OK button:

https://user-images.githubusercontent.com/1384259/182564428-1070ba57-52c5-4cde-b961-432c2dfc87cf.MOV

Is there any way to have further info about what's going on ?
Connection with my iPad went smoothly, tried remove/reinstall application ending with the same behavior

**Comment by MainasuK** [comment]
Hello. Sorry for the inconvenience. 
Some APIs are not available because our Twitter API token is marking limited now. 

Please check this announcement:
https://twitter.com/TwidereProject/status/1554403737191723008

Currently, only the Mastodon functions work.

**Comment by vmdude** [comment]
Thanks a lot for your quick response, I will follow the thread, thus closing this issue.

**Comment by MainasuK** [comment]
@vmdude @KinShin

We just temporary workaround that issue although the API still limited. So you could sign in now.

**Comment by vmdude** [comment]
That went well, you rock!

**Comment by KinShin** [comment]
@MainasuK Got it, thanks a lot.

**Comment by pylapp** [comment]
Thank you!
