### ISSUE TITLE
[BUG] fail to add account

### ISSUE THREAD

**Issue by KinShin** [TwidereProject/TwidereX-iOS#109]
I used to add 3 twitter accounts and when I just wanted to add one more I got a blank dialog and after clicking OK the page disappeared.

![A43491E9-1695-4B97-9CD3-93858DA58BA0](https://user-images.githubusercontent.com/6120853/182764555-9553720d-cdb6-47b6-905c-b6483463826e.jpeg)

**Comment by MainasuK** [comment]
Duplicated: https://github.com/TwidereProject/TwidereX-iOS/issues/107
