### ISSUE TITLE
[BUG] Not possible to tweet, retweet and fav 

### ISSUE THREAD

**Issue by pylapp** [TwidereProject/TwidereX-iOS#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I want to send a tweet, I got a forbidden red banner.

When I tap and retweet and fav buttons, I got vibrations like something failed, and the icons are not coloured.

### Expected Behavior

I should be able to send a tweet, retweeté and fav

### Steps To Reproduce

1. Open the app
2. Write a tweet
3. Try to send it using the button

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: iOS 15.4
- Version: V1.4.2
- Build: 117
- Domain: Twitter.com
```

### Anything else?

Keep going, I enjoy using your project ❤️

**Comment by MainasuK** [comment]
Sorry for the inconvenience. 

Please check #107. And you can sign in to the same account again to temporarily workaround it.

**Comment by pylapp** [comment]
Thank you a lot for your quick answer and the link of the old issue.
I followed the instructions and now it works again!

I close this issue.
