### ISSUE TITLE
[Feature request] Ability to change sort order in thread

### ISSUE THREAD

**Issue by vmdude** [TwidereProject/TwidereX-iOS#119]
The tweet order in the thread view seems to be newest on top, which makes it complicated when reading a multi-tweet thread.

![image](https://user-images.githubusercontent.com/1384259/192867200-364dc168-f6ab-4d42-8a2d-53c128400f7a.png)

Twitter app and website is the other way (oldest on top) which imho seems more "natural" when reading tweets in a thread.

It would be awesome if this sort behavior could be set as a parameter in the app.

Keep up the good work, thx 😁

**Comment by MainasuK** [comment]
The Twitter thread now display exactly likes a guest user to view in Twitter web app in v2.0.0 now.
