### ISSUE TITLE
Footer icon notice about replies is stretched 

### ISSUE THREAD

**Issue by pylapp** [TwidereProject/TwidereX-iOS#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given I tap on a tweet to display its details dans get it in plain screen
When the tweet is diplayed
Then the banner in the bottom of the tweet saying only mentioned accounts can reply has its leading icon stretched 

### Expected Behavior

The leading icon should not be stretched but squared 

### Steps To Reproduce

1. Launch the app
2. Tap on a specific tweet
3. See the bug 

![6FD204F2-92DC-4083-9E46-9CE8C623B11C](https://user-images.githubusercontent.com/7559007/197458691-81d10694-8657-4070-9ec3-024229a2f846.png)

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: iOS
- Version: 16.0.2
- Build: 1.4.3 (122)
- Domain: twitter.com
```

**Comment by MainasuK** [comment]
This part UI has been rewritten and the issue should be fixed in v2.0.0.
