### ISSUE TITLE
App icon can not be changed

### ISSUE THREAD

**Issue by Summerlve** [TwidereProject/TwidereX-iOS#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app icon can not be change even if I change it in settings, there’s nothing happened.

### Expected Behavior

App icon can be change.

### Steps To Reproduce

1.App settings 
2.App icon

### Environment

```markdown
- Device: iPhone 13
- OS: iOS 16.1.1
- Version: v1.4.3
- Build: 222
- Domain: mstdn.jp
```

**Comment by MainasuK** [comment]
Sorry. I can not reproduce it (I did try that long time ago). 

There is a icon changed alert displaying when you tapping the new icon. 
If you still have this problem. Please reopen it and I give me more detail (maybe a video record) to figure out what's wrong.
