### ISSUE TITLE
Crash wenn creating new toot

### ISSUE THREAD

**Issue by Inrumpo** [TwidereProject/TwidereX-iOS#127]
I'm experiencing an app crash when I try to create a new toot (Mastodon's equivalent of a tweet).

## Steps to reproduce:

1. Open the app
2. Make sure a Mastodon account is selected
3. Tap the quill-icon to compose a new toot
4. App is crashing (100% reproducible here)

## Environment

- iPad Pro 10.5
- iOS 15.7.1
- Twidere X for iOS 1.4.3 (122)

**Comment by MainasuK** [comment]
Sorry the late response. 

The v2.0.0 app was released and there is a new iPad layout UI. 
I test the app on iOS 16 and cannot reproduce this issue.

Please reopen it if you still have this problem. I'll try to figure out the reason.
Thanks.
