### ISSUE TITLE
[Bug] In conversation, the @ symbol is doubled for Twitter handles

### ISSUE THREAD

**Issue by pylapp** [TwidereProject/TwidereX-iOS#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given I want to display the list of Twitter accounts on a thread
When I get the list of the accounts
Then I see that the @ symbol is doubled for each account 

### Expected Behavior

For each Twitter account only on @ symbol should be displayed, not two

### Steps To Reproduce

1.  Choose a thread
2. Tap to the button to write a new tweet
3. Tap on text field listing members of the thread 
4. Get the list of users (see screenshot below)

![412A674B-E997-4076-9270-1344A7B5EFAB](https://user-images.githubusercontent.com/7559007/210398783-5ad23f7f-c452-43a1-89c0-ec9302f251aa.jpeg)

### Environment

```markdown
- Device: iPhone 14 Pro
- OS: iOS
- Version: 16.2
- Build: v1.4.3 (122)
- Domain: twitter.com
```

### Anything else?

Happy new year 🥳

**Comment by MainasuK** [comment]
Fixed in 01bc32f.
