### ISSUE TITLE
[BUG] Twitter re-login does not generate a new token

### ISSUE THREAD

**Issue by tohaklim** [TwidereProject/TwidereX-iOS#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Twitter API access appears to be broken, re-sign in does not generate a new token

### Expected Behavior

Twitter basic api works 

### Steps To Reproduce

1. Twidere X 1.4.3 (122), iOS 16.5
2. Attempt to log in into Twitter and update the timeline or perform tweet action (like, retweet etc)

### Environment

```markdown
- Device: iPhone 11 Mini
- OS: 16.5
- Version: 1.4.3
- Build: 122
- Domain: Twitter
```

**Comment by MainasuK** [comment]
Hi @tohaklim.

The token is returned if you could sign in the account into the home timeline. What's the "broken" you means. Is that any error block the sign in or cannot fetch the timeline? 

Also we have a beta. So maybe you could try this and check this issue again.
https://testflight.apple.com/join/GJIDXvW7

**Comment by MainasuK** [comment]
By the way. We not pay for the $5000/mouth Pro account for Twitter yet. So maybe the timeline is restricted to fetching now. But you could try skim the list timeline which still works now.

**Comment by tohaklim** [comment]
Thanks for the TestFlight link. The TestFlight version allows for tweet actions (retweet, like etc), but still doesn’t seem to fetch the timeline for me (as you say, likely due to Twitter limitations on non Pro account - although I have a few Twitter clients that still can fetch). The list doesn’t seem to load for me. I will close this as it’s a twitter issue
