### ISSUE TITLE
Improved font size settings

### ISSUE THREAD

**Issue by MainasuK** [TwidereProject/TwidereX-iOS#17]
Now the font size setting release in the DEBUG mode just works. More usable font size override controls should be refactored: the final font size calculated from the delta value base on the system font size.

**Comment by skjerns** [comment]
I second this, the font is rather large on a big screen, close to unreadable

**Comment by MainasuK** [comment]
The font size for content and many text components responses to system or app-specific settings in v.1.2.0 (67).

Please file in new issue if any controls not work with it.
