### ISSUE TITLE
Isn't it updated? 

### ISSUE THREAD

**Issue by wclmgcd** [TwidereProject/TwidereX-iOS#32]
It is still a semi-finished product, search is not available, personal page details cannot be used, and the progress is much worse than the Android version. Isn’t it updated?

**Comment by MainasuK** [comment]
The Twidere X for iOS will continue. Currently, I'm working on another [project](https://blog.joinmastodon.org/2021/02/developing-an-official-ios-app-for-mastodon/). The maintainers for this repo will resume soon.
