### ISSUE TITLE
iOS version discontinued?

### ISSUE THREAD

**Issue by gferreroferri** [TwidereProject/TwidereX-iOS#35]
Is iOS version discontinued? I see that Android version is already on 1.4 while iOS is still on iOS 1.1.2 without support for direct messages and not much customisation. Do you plan to continue iOS development? Thanks!

**Comment by MainasuK** [comment]
Duplicate #32 

Thank you for your attention. The project will continue once I'm available. I hope to make an update with iOS 15 but cannot guarantee that.
