### ISSUE TITLE
iPadOS (and possibly macOS) support?

### ISSUE THREAD

**Issue by TheQuinbox** [TwidereProject/TwidereX-iOS#52]
With the recent release of the M1 chip, it's become easier and easier to port iOS apps to Mac apps. I would love to see Twidere X on the Mac. Another way I know of is to use Catalyst (which converts your iPadOS app to a macOS one with very little fuss). Both options work quite well, and in fact Twitter uses Catalyst for their official app.

**Comment by MainasuK** [comment]
The current build works on the M1 Macs but not Intel Macs. 
You can download it in the App Store. It's not design for Mac and just works. 

And the iPad and Destop specific design are in the roadmap. It's still needs some times to do before the other features implemented.

**Comment by MainasuK** [comment]
@TheQuinbox The new iPad layout is available in v2.0.0. 
Please feedback if you have any idea. Thank you.
