### ISSUE TITLE
Profile background image not loaded in Profile tab

### ISSUE THREAD

**Issue by jk234ert** [TwidereProject/TwidereX-iOS#8]
Version:
TestFlight 0.11.3(33)

Bug Description:
The profile background image is not loaded on the Profile tab.

Step to reproduce:
1. Log in to any Twitter account
2. Tap the last tab bar button
3. Check the profile background image
4. Tap any users' avatar to navigate to their profile detail page, the profile background image is loaded correctly, even in myself's profile detail page.
![IMG_1943](https://user-images.githubusercontent.com/7972003/101303898-171eeb80-387a-11eb-97c8-87de660523e6.PNG)

![IMG_1944](https://user-images.githubusercontent.com/7972003/101303891-11290a80-387a-11eb-894e-9beed28465dc.PNG)

**Comment by MainasuK** [comment]
@jk234ert 
Can not reproduce this issue. Please check the network connection or try again.

**Comment by jk234ert** [comment]
After re-launching the app this issue could not be reproduced. The profile tab view (the 1st screenshot) does not auto-refresh when the view appears? If yes, IMO since this page is the root `UIViewController` of the profile tab, at least the basic profile info should be refreshed every time the profile page appears.

**Comment by MainasuK** [comment]
Profile info will update when the backend database changed. The image may fail to load from cache or network. Will add the avatar & banner image set checker. 

Marked as TODO.
